-- MySQL Script generated by MySQL Workbench
-- Tue Jun  7 19:36:07 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `profissao` VARCHAR(50) NOT NULL,
  `idade` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`atividade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`atividade` ;

CREATE TABLE IF NOT EXISTS `mydb`.`atividade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`espaco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`espaco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`espaco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `projetista` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`data` ;

CREATE TABLE IF NOT EXISTS `mydb`.`data` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `diaSemana` VARCHAR(10) NOT NULL,
  `dia` VARCHAR(2) NOT NULL,
  `mes` VARCHAR(10) NOT NULL,
  `ano` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fatoLocacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`fatoLocacao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`fatoLocacao` (
  `id` INT NOT NULL,
  `atividade_id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  `espaco_id` INT NOT NULL,
  `data_id` INT NOT NULL,
  `entrada` DATETIME NOT NULL,
  `saida` DATETIME NOT NULL,
  `tempoUtilizacao` DECIMAL(5,2) NOT NULL,
  `quantidadePessoa` INT NOT NULL,
  `custo` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_fatoLocacao_atividade_idx` (`atividade_id` ASC) VISIBLE,
  INDEX `fk_fatoLocacao_cliente1_idx` (`cliente_id` ASC) VISIBLE,
  INDEX `fk_fatoLocacao_espaco1_idx` (`espaco_id` ASC) VISIBLE,
  INDEX `fk_fatoLocacao_data1_idx` (`data_id` ASC) VISIBLE,
  CONSTRAINT `fk_fatoLocacao_atividade`
    FOREIGN KEY (`atividade_id`)
    REFERENCES `mydb`.`atividade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fatoLocacao_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `mydb`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fatoLocacao_espaco1`
    FOREIGN KEY (`espaco_id`)
    REFERENCES `mydb`.`espaco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fatoLocacao_data1`
    FOREIGN KEY (`data_id`)
    REFERENCES `mydb`.`data` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


